# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='instance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='output',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='probability',
            field=models.CharField(max_length=100),
        ),
    ]
