# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_trainingimage_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='/home/ellisr/Plancknew/Planck/PlanckApp/planck/planck/planck/static/default_image', upload_to=''),
        ),
    ]
